openapi: 3.2.0
info:
  title: OpenPanel Import API
  version: 1.0.0
  description: Import historical data
tags:
- name: Import
  description: Import historical data
paths:
  /import/events:
    post:
      tags:
      - Import
      description: Bulk import historical events.
      responses:
        '200':
          description: Default Response
      summary: Create import events
      x-summary-source: derived
      operationId: postImportEvents
      x-operation-id-source: derived
